export const Data = [
  {
    hotelName: "Luxury Suites",
    price: 2500,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "New York",
    popular: true,
    road: "123 Main Street",
    image: "luxury_suites.jpg",
  },
  {
    hotelName: "Cozy Inn",
    price: 1200,
    totalRoom: 30,
    popular: true,
    totalBeds: 60,
    totalBath: 30,
    roomSize: 300,
    city: "London",
    road: "456 Elm Avenue",
    image: "cozy_inn.jpg",
  },
  {
    hotelName: "Beachfront Resort",
    price: 3500,
    totalRoom: 80,
    totalBeds: 160,
    totalBath: 80,
    roomSize: 600,
    popular: true,
    city: "Miami",
    road: "789 Ocean Drive",
    image: "beachfront_resort.jpg",
  },
  {
    hotelName: "Downtown Plaza Hotel",
    price: 1800,
    totalRoom: 40,
    totalBeds: 80,
    totalBath: 40,
    roomSize: 350,
    city: "New York",
    road: "101 Pine Street",
    image: "downtown_plaza.jpg",
  },
  {
    hotelName: "Mountain View Lodge",
    price: 2200,
    totalRoom: 60,
    totalBeds: 120,
    totalBath: 60,
    roomSize: 500,
    city: "London",
    road: "567 Mountain Avenue",
    image: "mountain_view_lodge.jpg",
  },
  {
    hotelName: "Harborfront Suites",
    price: 2800,
    totalRoom: 70,
    totalBeds: 140,
    totalBath: 70,
    roomSize: 450,
    popular: true,
    city: "Denver",
    road: "987 Harbor Boulevard",
    image: "harborfront_suites.jpg",
  },
  {
    hotelName: "Riverside Retreat",
    price: 1900,
    totalRoom: 35,
    totalBeds: 70,
    totalBath: 35,
    roomSize: 320,
    city: "Denver",
    road: "321 River Lane",
    image: "riverside_retreat.jpg",
  },
  {
    hotelName: "Desert Oasis Resort",
    price: 3200,
    popular: true,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "New York",
    image: "desert_oasis_resort.jpg",
  },
  {
    hotelName: "Historic Mansion Inn",
    price: 1500,
    totalRoom: 25,
    totalBeds: 50,
    totalBath: 25,
    roomSize: 280,
    city: "London",
    road: "789 Historic Lane",
    image: "historic_mansion_inn.jpg",
  },
  {
    hotelName: "Historic Mansion Inn",
    price: 1500,
    totalRoom: 25,
    totalBeds: 50,
    totalBath: 25,
    roomSize: 280,
    city: "London",
    road: "789 Historic Lane",
    image: "historic_mansion_inn.jpg",
  },
  {
    hotelName: "Historic Mansion Inn",
    popular: true,
    price: 1500,
    totalRoom: 25,
    totalBeds: 50,
    totalBath: 25,
    roomSize: 280,
    city: "London",
    road: "789 Historic Lane",
    image: "historic_mansion_inn.jpg",
  },
  {
    hotelName: "Historic Mansion Inn",
    price: 1500,
    totalRoom: 25,
    totalBeds: 50,
    totalBath: 25,
    roomSize: 280,
    city: "London",
    road: "789 Historic Lane",
    image: "historic_mansion_inn.jpg",
  },
  {
    hotelName: "Historic Mansion Inn",
    price: 1500,
    totalRoom: 25,
    totalBeds: 50,
    totalBath: 25,
    roomSize: 280,
    popular: true,
    city: "London",
    road: "789 Historic Lane",
    image: "historic_mansion_inn.jpg",
  },
  {
    hotelName: "Historic Mansion Inn",
    price: 1500,
    totalRoom: 25,
    totalBeds: 50,
    popular: true,
    totalBath: 25,
    roomSize: 280,
    city: "London",
    road: "789 Historic Lane",
    image: "historic_mansion_inn.jpg",
  },
  {
    hotelName: "Seaside Villa",
    price: 2700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Seaside Villa",
    price: 2700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Desert Oasis Resort",
    price: 3200,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    popular: true,
    roomSize: 550,
    city: "Miami",
    road: "New York",
    image: "desert_oasis_resort.jpg",
  },
  {
    hotelName: "Desert Oasis Resort",
    price: 3200,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "New York",
    image: "desert_oasis_resort.jpg",
  },
  {
    hotelName: "Desert Oasis Resort",
    price: 3200,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "New York",
    image: "desert_oasis_resort.jpg",
  },
  {
    hotelName: "Desert Oasis Resort",
    price: 3200,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "New York",
    image: "desert_oasis_resort.jpg",
  },
  {
    hotelName: "Desert Oasis Resort",
    price: 3200,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    popular: true,
    road: "New York",
    image: "desert_oasis_resort.jpg",
  },
  {
    hotelName: "Seaside Villa",
    price: 2700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Seaside Villa",
    price: 2700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Seaside Villa",
    price: 2700,
    popular: true,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Seaside Villa",
    price: 2700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Seaside Villa",
    price: 2700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Seaside Villa",
    popular: true,
    price: 2700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Seaside Villa",
    price: 2700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Seaside Villa",
    price: 2700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 420,
    city: "Denver",
    road: "543 Beach Drive",
    image: "seaside_villa.jpg",
  },
  {
    hotelName: "Luxury Suites",
    price: 2500,
    popular: true,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "New York",
    road: "123 Main Street",
    image: "luxury_suites.jpg",
  },

  {
    popular: true,
    hotelName: "Luxury Suites",
    price: 2500,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "New York",
    road: "123 Main Street",
    image: "luxury_suites.jpg",
  },
  {
    hotelName: "Cityscape Hotel",
    price: 1700,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    roomSize: 330,
    city: "New York",
    road: "456 Downtown Avenue",
    image: "cityscape_hotel.jpg",
  },
  {
    popular: true,
    hotelName: "Mountain Retreat",
    price: 2400,
    totalRoom: 65,
    totalBeds: 130,
    totalBath: 65,
    roomSize: 480,
    city: "London",
    road: "789 Mountain Road",
    image: "mountain_retreat.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    popular: true,
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Luxury Suites",
    price: 2500,
    popular: true,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "New York",
    road: "123 Main Street",
    image: "luxury_suites.jpg",
  },
  {
    hotelName: "Luxury Suites",
    price: 2500,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "New York",
    road: "123 Main Street",
    image: "luxury_suites.jpg",
  },
  {
    hotelName: "Luxury Suites",
    price: 2500,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "New York",
    road: "123 Main Street",
    image: "luxury_suites.jpg",
  },
  {
    hotelName: "Luxury Suites",
    price: 2500,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "New York",
    road: "123 Main Street",
    image: "luxury_suites.jpg",
  },
  {
    hotelName: "Luxury Suites",
    price: 2500,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "New York",
    road: "123 Main Street",
    image: "luxury_suites.jpg",
  },
  {
    hotelName: "Luxury Suites",
    price: 2500,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "New York",
    popular: true,
    road: "123 Main Street",
    image: "luxury_suites.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    popular: true,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    popular: true,
    roomSize: 550,
    city: "Miami",
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    popular: true,
    roomSize: 550,
    city: "Miami",
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Beachside Resort",
    price: 3100,
    popular: true,
    totalRoom: 75,
    totalBeds: 150,
    totalBath: 75,
    roomSize: 550,
    city: "Miami",
    road: "234 Beachfront Avenue",
    image: "beachside_resort.jpg",
  },
  {
    hotelName: "Rustic Cabin Lodge",
    price: 1600,
    totalRoom: 30,
    totalBeds: 60,
    totalBath: 30,
    roomSize: 280,
    city: "Miami",
    road: "567 Cabin Lane",
    image: "rustic_cabin_lodge.jpg",
  },
  {
    hotelName: "Rustic Cabin Lodge",
    price: 1600,
    totalRoom: 30,
    totalBeds: 60,
    totalBath: 30,
    roomSize: 280,
    city: "Miami",
    road: "567 Cabin Lane",
    image: "rustic_cabin_lodge.jpg",
  },
  {
    hotelName: "Rustic Cabin Lodge",
    popular: true,
    price: 1600,
    totalRoom: 30,
    totalBeds: 60,
    totalBath: 30,
    roomSize: 280,
    city: "Miami",
    road: "567 Cabin Lane",
    image: "rustic_cabin_lodge.jpg",
  },
  {
    hotelName: "Garden Oasis Inn",
    price: 2100,
    totalRoom: 40,
    totalBeds: 80,
    totalBath: 40,
    roomSize: 360,
    city: "New York",
    road: "345 Garden Street",
    image: "garden_oasis_inn.jpg",
  },
  {
    hotelName: "Urban Retreat Hotel",
    price: 1900,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "London",
    road: "678 Urban Avenue",
    image: "urban_retreat_hotel.jpg",
  },
  {
    hotelName: "Urban Retreat Hotel",
    price: 1900,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    popular: true,
    city: "London",
    road: "678 Urban Avenue",
    image: "urban_retreat_hotel.jpg",
  },
  {
    hotelName: "Urban Retreat Hotel",
    price: 1900,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "London",
    road: "678 Urban Avenue",
    image: "urban_retreat_hotel.jpg",
  },
  {
    hotelName: "Urban Retreat Hotel",
    price: 1900,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    popular: true,
    roomSize: 400,
    city: "London",
    road: "678 Urban Avenue",
    image: "urban_retreat_hotel.jpg",
  },
  {
    hotelName: "Urban Retreat Hotel",
    price: 1900,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "London",
    road: "678 Urban Avenue",
    image: "urban_retreat_hotel.jpg",
  },
  {
    hotelName: "Urban Retreat Hotel",
    price: 1900,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    popular: true,
    city: "London",
    road: "678 Urban Avenue",
    image: "urban_retreat_hotel.jpg",
  },
  {
    hotelName: "Urban Retreat Hotel",
    price: 1900,
    totalRoom: 50,
    totalBeds: 100,
    totalBath: 50,
    roomSize: 400,
    city: "London",
    road: "678 Urban Avenue",
    image: "urban_retreat_hotel.jpg",
  },
  {
    hotelName: "Mountain View Inn",
    price: 2300,
    totalRoom: 55,
    totalBeds: 110,
    totalBath: 55,
    popular: true,
    roomSize: 450,
    city: "Miami",
    road: "123 Mountain View Road",
    image: "urban_retreat_hotel.jpg",
  },
];
